version: 0.0
os: linux
files:
  - source: .
    destination: /home/despliegues/front
permissions:
  - object: /home/despliegues/front
    owner: root
    mode: 755
ApplicationStart:
  - location: scripts/start_service.sh
    timeout: 600
    runas: root
