version: 0.0
os: linux
files:
  - source: .
    destination: /home/despliegues/Sistema_Administrativo/front
permissions:
  - object: /home/despliegues/Sistema_Administrativo/front
#    owner: consuladmin
    mode: 777
hooks:
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 600
      runas: root
