export const environment = {
  production: true,
  apiHost: 'https://administracion.consulpagos.com',
  puerto_sesion: "",
  puerto_usuarios: "",
  puerto_ventas: "",
  puerto_pagos: "",
  puerto_bancario: "",
  puerto_clientes: "",
  puerto_inventario: "",
  puerto_archive: "",
  divider: "",

  J_KEY: 'vsPlT8h1qZhMh3gxT0vi4htLMuLvrRRQ',
  J_VEC: 'No4cWnM5PQx0zOLB',
  S_KEY: "mg5tkziWFsb6trO24DEsRpj00Zj3BV5u",
  S_VEC: 'DVpJyVqn2NvUNGDt',
  ST_KEY: "NlzvzhuZCcxAwQpbtBjR6JsIo2YJe52Y",
  ST_VEC: "3KhhLvac7GAvrKoB",
};
